name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        cd ../frontend
        npm install
        
    - name: Run tests
      run: |
        cd backend
        python -m pytest
        cd ../frontend
        npm test
        
    - name: Deploy to Raspberry Pi
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RASPBERRY_IP }}
        username: ${{ secrets.RASPBERRY_USER }}
        key: ${{ secrets.RASPBERRY_SSH_KEY }}
        script: |
          cd /var/www/aulas-resilientes
          git pull origin main
          systemctl restart aulas-resilientes
